model:
  name: "ablation_studies"
  version: "ablation"

  common:
    dropout_rate: 0.2

  # Grid network parameters
  grid:
    model: "se3" # 'se3', 'egnn', 'egnn_attention', 'egnn_coords'
    num_layers_grid: 5 # 5 for 'se3'
    l0_in_features: 102
    n_heads: 4
    num_channels: 32
    num_edge_features: 3
    l0_out_features: 64
    ntypes: 6

  # Ligand network parameters
  ligand:
    model: "gat"  # Model type for ligand processing
    num_layers: 4
    l0_in_features: 18
    l0_out_features: 64
    n_heads: 4
    num_channels: 32
    num_edge_features: 5
    n_lig_global_in: 19
    n_lig_global_out: 4

  # trigonal related, but output dims can affect other modules (e.g., ClassModule)
  TR:
    d: 64
    # m: 64 (removed - now uses featurizer output dimensions)
    c: 64
    n_trigon_lig_layers: 2
    n_trigon_key_layers: 3
    shared_trigon: false
    normalize_Xform: true
    lig_to_key_attn: true
    trigon_module: 'trigon' # 'optimized'

  aff:
    classification_mode: "former_contrast"

# Training parameters
training:
  load_checkpoint: false
  lr: 1.0e-5
  max_epoch: 500
  accumulation_steps: 1
  debug: false
  ddp: true
  silent: false
  amp: false
  wandb_mode: "online"  # Options: "online", "disabled", "offline"
  weight_decay: 1.0e-4  # L2 regularization via optimizer weight decay
  max_param_norm: 20.0  # Maximum parameter norm before warning
  custom_init: false  # Custom initialization flag, can be used to trigger specific init logic
  
  # Learning rate scheduler configuration
  scheduler:
    use_scheduler: true
    scheduler_type: "ReduceLROnPlateau"  # Options: "ReduceLROnPlateau", "StepLR", "CosineAnnealingLR", "None"
    # ReduceLROnPlateau parameters
    factor: 0.8          # Factor by which LR is reduced
    patience: 3          # Number of epochs with no improvement after which LR is reduced
    min_lr: 1.0e-6       # Minimum learning rate
    threshold: 1.0e-4    # Threshold for measuring new optimum
    # StepLR parameters (used if scheduler_type is "StepLR")
    step_size: 50        # Period of learning rate decay
    gamma: 0.1           # Multiplicative factor of learning rate decay
    # CosineAnnealingLR parameters (used if scheduler_type is "CosineAnnealingLR")
    T_max: 100           # Maximum number of iterations

# Data parameters
data:
  datapath: "/home/j2ho/DB/for_msk/"
  train_file: "data/msk_train_sub.txt"
  valid_file: "data/msk_valid_sub.txt"
  affinityf: "data/affinity.npz"
  decoyf: "decoys.BL2.npz"
  crossreceptorf: "crossreceptor.filtered.npz"
  keyatomf: "keyatom.def.npz"
  ball_radius: 8.0
  edgedist: [2.2, 4.5]
  edgemode: "topk"
  edgek: [8, 16]
  randomize: 0.2
  ntype: 6
  maxedge: 40000
  maxnode: 3000
  drop_H: true
  max_subset: 5

# Data loader parameters
dataloader:
  batch_size: 1
  num_workers: 4
  pin_memory: true
  shuffle: true

# Loss weights
losses:
  w_cat: 0.05 #wGrid
  w_str: 0.2 #wTr 
  w_penalty: 1.0e-8 #w_reg
  w_contrast: 2.0
  w_spread: 5.0
  w_screen: 0.5
  w_screen_contrast: 0.5
  w_screen_ranking: 5.0
  w_Dkey: 1.0
  screenloss: "BCE"
  struct_loss: "mse"

# Ablation study configuration
ablation:
  # Module ablations
  enable_structure_module: false      # Enable/disable StructModule
  enable_keyatom_trimming: false      # Enable/disable trimming to key atoms
  enable_lig_to_key_attn: true       # Enable/disable ligand-to-key attention
  enable_trigon_lig: true            # Enable/disable initial trigon module on all ligand atoms
  enable_trigon_key_layers: true     # Enable/disable trigon layers for key atoms
  enable_xform_modules: true         # Enable/disable XformModule layers
  enable_distance_transform: true    # Enable/disable DistanceModule
  
  # Loss function ablations (set weight to 0 to disable)
  ablate_cat_loss: false            # Set w_cat to 0 if true
  ablate_structure_loss: false      # Set w_str to 0 if true  
  ablate_contrast_loss: false       # Set w_contrast to 0 if true
  ablate_spread_loss: false         # Set w_spread to 0 if true
  ablate_screen_loss: false         # Set w_screen to 0 if true
  ablate_screen_contrast_loss: false # Set w_screen_contrast to 0 if true
  ablate_screen_ranking_loss: false # Set w_screen_ranking to 0 if true
  ablate_dkey_loss: false           # Set w_Dkey to 0 if true
  
  # Component-specific ablations
  skip_grid_projection: false       # Skip linear projection for grid features
  skip_key_projection: false        # Skip linear projection for key features
  num_trigon_key_layers: null       # Override n_trigon_key_layers if set (null uses config value)
  num_trigon_lig_layers: null       # Override n_trigon_lig_layers if set (null uses config value)


# Cross-validation and data augmentation
cross_validation:
  load_cross: true
  cross_eval_struct: true
  cross_grid: 1.0
  nonnative_struct_weight: 0.2

# Other data settings
misc:
  pert: true
  randomize_grid: 0.0
  firstshell_as_grid: false
  use_input_PHcore: false
